name: Deploy Angular Application

on:
  push:
    branches: [ main ]  # Change this to match your default branch name (e.g., main or master)
  pull_request:
    branches: [ main ]  # Change this to match your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for github-pages-deploy-action
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Using Node.js 20.x for better compatibility with Angular 19
        cache: 'npm'
    
    - name: Get repository name
      id: get-repo-name
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
        echo "OWNER_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 1)" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: npm ci
      
    - name: Update base-href in scripts
      run: |
        sed -i "s|https://nilabhsubramaniam.github.io/ida/|https://${{ env.OWNER_NAME }}.github.io/${{ env.REPO_NAME }}/|g" package.json

    - name: Build Angular project with hash routing
      run: |
        # First copy the hash routing config
        cp src/app/app.config.hash.ts src/app/app.config.ts
        # Then build with hash routing
        npm run build:prod -- --base-href "/${{ env.REPO_NAME }}/"
    
    - name: Debug build output
      run: |
        echo "Build output directory structure:"
        ls -la dist/
        ls -la dist/vyaktigatav-rtta/ || echo "Main output directory not found"
        
    - name: Copy additional files to distribution folder
      run: |
        # Angular 17+ builds to a browser subdirectory - make sure all files are in the right place
        echo "Moving files from browser directory to root..."
        find dist/vyaktigatav-rtta/browser -mindepth 1 -maxdepth 1 -exec mv {} dist/vyaktigatav-rtta/ \;
        rm -rf dist/vyaktigatav-rtta/browser
        
        # Create required directories if they don't exist
        mkdir -p dist/vyaktigatav-rtta/assets
        
        # Create .nojekyll file to disable Jekyll processing
        touch dist/vyaktigatav-rtta/.nojekyll
        
        # Use direct Angular app instead of redirects
        # The hash-based routing is already configured in the Angular app
        cp -f public/.nojekyll dist/vyaktigatav-rtta/
        
        # Copy .htaccess for Apache servers if it exists
        cp -f public/.htaccess dist/vyaktigatav-rtta/ || echo "No .htaccess file to copy"
        
        # Create a verification file to confirm deployment
        echo "v$(date +'%Y%m%d%H%M')" > dist/vyaktigatav-rtta/version.txt
        
        # Only copy essential files needed for production
        echo "Adding minimal documentation"
        echo "# व्यक्तिगतवृत्त Resume Builder" > dist/vyaktigatav-rtta/README.md
        
        # Ensure assets are properly copied
        echo "Setting up assets for deployment..."
        if [ -d "public/assets" ]; then
          mkdir -p dist/vyaktigatav-rtta/assets
          cp -rf public/assets/* dist/vyaktigatav-rtta/assets/ || echo "No assets to copy"
          echo "✅ Assets copied successfully"
          ls -la dist/vyaktigatav-rtta/assets/
          
          # Fix asset URLs in CSS files for GitHub Pages deployment
          echo "Fixing asset URLs in CSS files..."
          
          # Find all CSS files
          CSSFILES=$(find "dist/vyaktigatav-rtta" -name "*.css")
          
          # For each CSS file, replace absolute asset paths with relative ones
          for file in $CSSFILES; do
            echo "Processing $file"
            # Replace "/assets/" with "assets/" (remove leading slash)
            sed -i 's|url(/assets/|url(assets/|g' "$file"
            echo "✅ Fixed asset paths in $(basename "$file")"
          done
        else
          echo "⚠️ WARNING: No assets directory found in public/"
        fi
        
        # Copy assets from src/assets if they exist
        if [ -d "src/assets" ]; then
          mkdir -p dist/vyaktigatav-rtta/assets
          cp -rf src/assets/* dist/vyaktigatav-rtta/assets/ || echo "No src assets to copy"
          echo "✅ Src assets copied successfully"
        fi
        
        # Copy CNAME file if it exists
        cp -f public/CNAME dist/vyaktigatav-rtta/ || echo "No CNAME file to copy"
        
        # Create a sitemap.xml for SEO
        SITE_URL="https://$OWNER_NAME.github.io/$REPO_NAME/"
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
        <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">
          <url><loc>$SITE_URL</loc></url>
        </urlset>" > dist/vyaktigatav-rtta/sitemap.xml
        
        # Create a robots.txt file
        echo "User-agent: *
        Allow: /" > dist/vyaktigatav-rtta/robots.txt
        
        # Copy assets directory
        if [ -d "public/assets" ]; then
          cp -rf public/assets/* dist/vyaktigatav-rtta/assets/ || echo "No asset files to copy"
        fi
        
        # Create a version file with timestamp
        echo "v$(date +'%Y%m%d%H%M')" > dist/vyaktigatav-rtta/version.txt
        
        # Create .nojekyll file to disable Jekyll processing on GitHub Pages
        touch dist/vyaktigatav-rtta/.nojekyll
        
        # Verify the build files are properly set up
        echo "Verifying Angular build files:"
        grep -q "<app-root" dist/vyaktigatav-rtta/index.html && echo "✅ Angular app root found" || echo "❌ Angular app root not found"
        
        echo "Verifying hash routing is enabled:"
        grep -q "base href=\"/ida/\"" dist/vyaktigatav-rtta/index.html && echo "✅ Base href is set" || echo "❌ Base href not found"
        
        # Check that main JavaScript file exists
        find dist/vyaktigatav-rtta -name "main-*.js" | grep -q . && echo "✅ Main JS file found" || echo "❌ Main JS file not found"
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/vyaktigatav-rtta  # Your Angular output directory
        branch: gh-pages
        clean: true  # Automatically remove deleted files from the deployment
