name: Deploy Angular Application

on:
  push:
    branches: [ main ]  # Change this to match your default branch name (e.g., main or master)
  pull_request:
    branches: [ main ]  # Change this to match your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for github-pages-deploy-action
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Using Node.js 20.x for better compatibility with Angular 19
        cache: 'npm'
    
    - name: Get repository name
      id: get-repo-name
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
        echo "OWNER_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 1)" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: npm ci
      
    - name: Update base-href in scripts
      run: |
        sed -i "s|https://nilabhsubramaniam.github.io/ida/|https://${{ env.OWNER_NAME }}.github.io/${{ env.REPO_NAME }}/|g" package.json

    - name: Build Angular project
      run: |
        npm run build:prod -- --base-href "/${{ env.REPO_NAME }}/"
    
    - name: Debug build output
      run: |
        echo "Build output directory structure:"
        ls -la dist/
        ls -la dist/vyaktigatav-rtta/ || echo "Main output directory not found"
        
    - name: Copy additional files to distribution folder
      run: |
        # Create required directories
        mkdir -p dist/vyaktigatav-rtta/assets
        
        # Create .nojekyll file to disable Jekyll processing
        touch dist/vyaktigatav-rtta/.nojekyll
        
        # Copy index.html to root - important for GitHub Pages
        cp -f public/index.html dist/vyaktigatav-rtta/index.html
        
        # Copy files for client-side routing support in GitHub Pages
        cp -f public/404.html dist/vyaktigatav-rtta/
        cp -f public/.nojekyll dist/vyaktigatav-rtta/
        
        # Copy .htaccess for Apache servers if it exists
        cp -f public/.htaccess dist/vyaktigatav-rtta/ || echo "No .htaccess file to copy"
        
        # Create a verification file to confirm deployment
        echo "v$(date +'%Y%m%d%H%M')" > dist/vyaktigatav-rtta/version.txt
        
        # Copy test pages and documentation
        cp -f public/test.html dist/vyaktigatav-rtta/
        cp -f public/deploy-test.html dist/vyaktigatav-rtta/
        cp -f public/routing-test.html dist/vyaktigatav-rtta/
        cp -f public/GITHUB-PAGES-README.md dist/vyaktigatav-rtta/README.md
        
        # Ensure assets are copied properly
        if [ -d "public/assets" ]; then
          cp -rf public/assets/* dist/vyaktigatav-rtta/assets/ || echo "No assets to copy"
          echo "Assets copied successfully"
          ls -la dist/vyaktigatav-rtta/assets/
        else
          echo "No assets directory found in public/"
        fi
        
        # Copy CNAME file if it exists
        cp -f public/CNAME dist/vyaktigatav-rtta/ || echo "No CNAME file to copy"
        
        # Create a sitemap.xml for SEO
        SITE_URL="https://$OWNER_NAME.github.io/$REPO_NAME/"
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
        <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">
          <url><loc>$SITE_URL</loc></url>
        </urlset>" > dist/vyaktigatav-rtta/sitemap.xml
        
        # Create a robots.txt file
        echo "User-agent: *
        Allow: /" > dist/vyaktigatav-rtta/robots.txt
        
        # Copy assets directory
        if [ -d "public/assets" ]; then
          cp -rf public/assets/* dist/vyaktigatav-rtta/assets/ || echo "No asset files to copy"
        fi
        
        # Create a version file with timestamp
        echo "v$(date +'%Y%m%d%H%M')" > dist/vyaktigatav-rtta/version.txt
        
        # Create .nojekyll file to disable Jekyll processing on GitHub Pages
        touch dist/vyaktigatav-rtta/.nojekyll
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/vyaktigatav-rtta  # Your Angular output directory
        branch: gh-pages
        clean: true  # Automatically remove deleted files from the deployment
